# Generated by Django 3.0.3 on 2020-02-06 13:04

from django.db import migrations


def forwards_func(apps, schema_editor):
    Veterinarian = apps.get_model('pet_vet', 'Veterinarian')
    db_alias = schema_editor.connection.alias
    Veterinarian.objects.using(db_alias).bulk_create([
        Veterinarian(title_prefix='MVDr.', first_name='Daniel', last_name='Ptáček', specialization='Papoušci, Hadi'),
        Veterinarian(title_prefix='MVDr.', first_name='František', last_name='Vopička', specialization='Kočky, Psi'),
        Veterinarian(title_prefix='MVDr.', first_name='Milan', last_name='Pěnkava', title_suffix='Ph.D.', specialization='Kočky, Psi, Velryby'),
        Veterinarian(title_prefix='MVDr.', first_name='Alice', last_name='Srstková', specialization='Psi, Papoušci'),
        Veterinarian(title_prefix='MVDr.', first_name='Tereza', last_name='Chloupková', specialization='Křečci, Hadi, Velryby'),
        Veterinarian(title_prefix='MVDr.', first_name='Marie', last_name='Tlapková', title_suffix='Ph.D.', specialization='Kočky, Psi, Hadi'),
    ])


def reverse_func(apps, schema_editor):
    Veterinarian = apps.get_model('pet_vet', 'Veterinarian')
    db_alias = schema_editor.connection.alias
    Veterinarian.objects.using(db_alias).filter(title_prefix='MVDr.', first_name='Daniel', last_name='Ptáček', specialization='Papoušci, Hadi').delete()
    Veterinarian.objects.using(db_alias).filter(title_prefix='MVDr.', first_name='František', last_name='Vopička', specialization='Kočky, Psi').delete()
    Veterinarian.objects.using(db_alias).filter(title_prefix='MVDr.', first_name='Milan', last_name='Pěnkava', title_suffix='Ph.D.', specialization='Kočky, Psi, Velryby').delete()
    Veterinarian.objects.using(db_alias).filter(title_prefix='MVDr.', first_name='Alice', last_name='Srstková', specialization='Psi, Papoušci').delete()
    Veterinarian.objects.using(db_alias).filter(title_prefix='MVDr.', first_name='Tereza', last_name='Chloupková', specialization='Křečci, Hadi, Velryby').delete()
    Veterinarian.objects.using(db_alias).filter(title_prefix='MVDr.', first_name='Marie', last_name='Tlapková', title_suffix='Ph.D.', specialization='Kočky, Psi, Hadi').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('pet_vet', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
