# Generated by Django 3.0.3 on 2020-02-06 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Veterinarian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_prefix', models.CharField(blank=True, max_length=32, null=True, verbose_name='tituly před')),
                ('first_name', models.CharField(max_length=64, verbose_name='jméno')),
                ('last_name', models.CharField(max_length=64, verbose_name='příjmení')),
                ('title_suffix', models.CharField(blank=True, max_length=32, null=True, verbose_name='tituly za')),
                ('specialization', models.CharField(max_length=128, verbose_name='specializace')),
            ],
            options={
                'verbose_name': 'Veterinář',
                'verbose_name_plural': 'Veterináři',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='datum návštěvy')),
                ('name', models.CharField(max_length=128, verbose_name='jméno a příjmení')),
                ('phone', models.CharField(max_length=16, verbose_name='telefon')),
                ('email', models.CharField(blank=True, max_length=64, null=True, verbose_name='e-mail')),
                ('pet_type', models.CharField(choices=[('SNAKE', 'Had'), ('CAT', 'Kočka'), ('HAMSTER', 'Křeček'), ('PARROT', 'Papoušek'), ('DOG', 'Pes'), ('WHALE', 'Velryba')], max_length=16, verbose_name='druh mazlíčka')),
                ('preferred_vet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pet_vet.Veterinarian', verbose_name='preferovaný veterinář')),
            ],
            options={
                'verbose_name': 'Návštěva',
                'verbose_name_plural': 'Návštěvy',
                'ordering': ['-date', 'pet_type', 'name'],
            },
        ),
    ]
